<?php
declare(strict_types=1);
session_start();
$base=__DIR__;
foreach([$base.'/config/config.php',$base.'/config.php'] as $f){if(is_file($f)){require_once $f;break;}}
if(!isset($pdo)||!($pdo instanceof PDO)){http_response_code(500);exit('PDO no disponible.');}
$done=[];$errors=[];
function run(PDO $pdo,string $sql,string $label,array &$done,array &$errors):void{try{$pdo->exec($sql);$done[]=$label;}catch(Throwable $e){$errors[]=$label.': '.$e->getMessage();}}
if($_SERVER['REQUEST_METHOD']==='POST'){
run($pdo,"CREATE TABLE IF NOT EXISTS persona_rep_snapshots (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,persona_id BIGINT UNSIGNED NOT NULL,actividad_id BIGINT UNSIGNED DEFAULT NULL,cedula_normalizada VARCHAR(40) NOT NULL,fuente VARCHAR(120) DEFAULT 'electores',fuente_version VARCHAR(80) DEFAULT NULL,snapshot_json LONGTEXT NOT NULL,snapshot_hash CHAR(64) NOT NULL,consultado_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_snapshot_persona(persona_id),KEY idx_snapshot_actividad(actividad_id),KEY idx_snapshot_cedula(cedula_normalizada),KEY idx_snapshot_hash(snapshot_hash)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'Tabla de snapshots REP',$done,$errors);
run($pdo,"CREATE TABLE IF NOT EXISTS persona_vinculacion_actual (persona_id BIGINT UNSIGNED NOT NULL,tipo_instancia VARCHAR(60) NOT NULL,tabla_origen VARCHAR(120) NOT NULL,registro_origen_id BIGINT UNSIGNED DEFAULT NULL,cargo VARCHAR(220) DEFAULT NULL,estado VARCHAR(120) DEFAULT NULL,municipio VARCHAR(160) DEFAULT NULL,parroquia VARCHAR(180) DEFAULT NULL,fecha_inicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(persona_id),KEY idx_vinc_tipo(tipo_instancia),KEY idx_vinc_territorio(estado,municipio,parroquia)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'Vinculación organizativa actual',$done,$errors);
run($pdo,"CREATE TABLE IF NOT EXISTS persona_vinculaciones_historial (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,persona_id BIGINT UNSIGNED NOT NULL,tipo_instancia VARCHAR(60) NOT NULL,tabla_origen VARCHAR(120) NOT NULL,registro_origen_id BIGINT UNSIGNED DEFAULT NULL,cargo VARCHAR(220) DEFAULT NULL,estado VARCHAR(120) DEFAULT NULL,municipio VARCHAR(160) DEFAULT NULL,parroquia VARCHAR(180) DEFAULT NULL,fecha_inicio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,fecha_fin DATETIME DEFAULT NULL,estatus VARCHAR(40) NOT NULL DEFAULT 'ACTIVO',motivo_fin VARCHAR(220) DEFAULT NULL,datos_json LONGTEXT DEFAULT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_vh_persona(persona_id),KEY idx_vh_tipo(tipo_instancia),KEY idx_vh_estatus(estatus)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'Historial de vinculaciones',$done,$errors);
run($pdo,"CREATE TABLE IF NOT EXISTS expediente360_inconsistencias (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,cedula_normalizada VARCHAR(40) NOT NULL,persona_id BIGINT UNSIGNED DEFAULT NULL,tipo VARCHAR(100) NOT NULL DEFAULT 'DOBLE_VINCULACION_ACTIVA',detalle_json LONGTEXT DEFAULT NULL,estatus VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE',detectado_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resuelto_at DATETIME DEFAULT NULL,PRIMARY KEY(id),UNIQUE KEY uq_inc_activa(cedula_normalizada,tipo,estatus),KEY idx_inc_estado(estatus)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'Bandeja de inconsistencias',$done,$errors);
$alters=[
"ALTER TABLE actividad_asistencias ADD COLUMN IF NOT EXISTS snapshot_rep_id BIGINT UNSIGNED DEFAULT NULL",
"ALTER TABLE actividad_asistencias ADD COLUMN IF NOT EXISTS clasificacion_al_registro VARCHAR(40) DEFAULT NULL",
"ALTER TABLE actividad_asistencias ADD COLUMN IF NOT EXISTS vinculacion_tipo_al_registro VARCHAR(60) DEFAULT NULL",
"ALTER TABLE personas ADD COLUMN IF NOT EXISTS clasificacion_actual VARCHAR(40) DEFAULT 'SIMPATIZANTE'",
"ALTER TABLE personas ADD COLUMN IF NOT EXISTS tipo_vinculacion_actual VARCHAR(60) DEFAULT NULL",
"ALTER TABLE personas ADD COLUMN IF NOT EXISTS cantidad_actividades INT NOT NULL DEFAULT 0"
];foreach($alters as $i=>$sql)run($pdo,$sql,'Ajuste '.($i+1),$done,$errors);
// Recalcular expedientes existentes por estructura y redes.
try{
 $pdo->exec("UPDATE personas p SET p.es_activista=CASE WHEN EXISTS(SELECT 1 FROM estructuras_miembros em WHERE CAST(REPLACE(REPLACE(REPLACE(em.cedula,'.',''),'V',''),'E','') AS UNSIGNED)=CAST(p.cedula_normalizada AS UNSIGNED) AND em.activo=1 AND UPPER(COALESCE(em.estatus,'ACTIVO')) NOT IN('INACTIVO','RETIRADO','FINALIZADO','VACANTE')) OR EXISTS(SELECT 1 FROM redes_populares_miembros rm WHERE CAST(REPLACE(REPLACE(REPLACE(rm.cedula,'.',''),'V',''),'E','') AS UNSIGNED)=CAST(p.cedula_normalizada AS UNSIGNED) AND UPPER(COALESCE(rm.estatus,'ACTIVO')) NOT IN('INACTIVO','RETIRADO','FINALIZADO','VACANTE')) THEN 1 ELSE 0 END");
 $pdo->exec("UPDATE personas SET clasificacion_actual=IF(es_activista=1,'ACTIVISTA','SIMPATIZANTE'),clasificacion_general=IF(es_activista=1,'ACTIVISTA','SIMPATIZANTE')");
 $done[]='Clasificación Activista/Simpatizante recalculada';
}catch(Throwable $e){$errors[]='Clasificación: '.$e->getMessage();}
// Detectar dobles vinculaciones entre estructuras y redes.
try{
 $sql="INSERT IGNORE INTO expediente360_inconsistencias(cedula_normalizada,persona_id,tipo,detalle_json,estatus,detectado_at) SELECT p.cedula_normalizada,p.id,'DOBLE_VINCULACION_ACTIVA',JSON_OBJECT('estructura',1,'red_popular',1),'PENDIENTE',NOW() FROM personas p WHERE EXISTS(SELECT 1 FROM estructuras_miembros em WHERE CAST(REPLACE(REPLACE(REPLACE(em.cedula,'.',''),'V',''),'E','') AS UNSIGNED)=CAST(p.cedula_normalizada AS UNSIGNED) AND em.activo=1 AND UPPER(COALESCE(em.estatus,'ACTIVO')) NOT IN('INACTIVO','RETIRADO','FINALIZADO','VACANTE')) AND EXISTS(SELECT 1 FROM redes_populares_miembros rm WHERE CAST(REPLACE(REPLACE(REPLACE(rm.cedula,'.',''),'V',''),'E','') AS UNSIGNED)=CAST(p.cedula_normalizada AS UNSIGNED) AND UPPER(COALESCE(rm.estatus,'ACTIVO')) NOT IN('INACTIVO','RETIRADO','FINALIZADO','VACANTE'))";
 $pdo->exec($sql);$done[]='Inconsistencias organizativas detectadas';
}catch(Throwable $e){$errors[]='Inconsistencias: '.$e->getMessage();}
// Insertar acceso al menú de manera no destructiva.
foreach([$base.'/includes/layout.php',$base.'/includes/sidebar.php',$base.'/includes/menu.php',$base.'/partials/sidebar.php'] as $menu){
 if(!is_file($menu))continue;$txt=file_get_contents($menu);if(strpos($txt,'expediente360.php')!==false)continue;
 $item="\n<!-- Expediente 360 V10 -->\n<a href=\"expediente360.php\" class=\"nav-link e360-menu-link\"><span class=\"nav-icon\">◉</span><span>Expediente 360°</span></a>\n";
 $pos=strripos($txt,'</nav>');if($pos!==false)$txt=substr($txt,0,$pos).$item.substr($txt,$pos);else $txt.=$item;
 if(@file_put_contents($menu,$txt)!==false)$done[]='Menú actualizado: '.basename($menu);else$errors[]='No se pudo actualizar '.basename($menu);
 break;
}
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Instalador Expediente 360 V10</title><style>body{font-family:Inter,Arial;background:#f4f6fa;margin:0;color:#182033}.wrap{max-width:900px;margin:40px auto;padding:20px}.card{background:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 50px #13213a18}.brand{color:#f28c18;font-weight:900;letter-spacing:.08em}.btn{background:#f28c18;border:0;color:#fff;padding:14px 20px;border-radius:12px;font-weight:800;cursor:pointer}.ok{background:#edfff4;border:1px solid #9fe4bb;padding:12px;border-radius:12px;margin:8px 0}.err{background:#fff0f0;border:1px solid #f1a5a5;padding:12px;border-radius:12px;margin:8px 0}code{background:#eef1f6;padding:3px 6px;border-radius:6px}</style></head><body><div class="wrap"><div class="card"><div class="brand">VPNACIONAL</div><h1>Expediente 360° · Instalador V10</h1><p>Crea la trazabilidad, snapshots completos del REP, clasificación Activista/Simpatizante y control de una sola vinculación activa.</p><?php foreach($done as $x):?><div class="ok">✓ <?=htmlspecialchars($x)?></div><?php endforeach;?><?php foreach($errors as $x):?><div class="err">⚠ <?=htmlspecialchars($x)?></div><?php endforeach;?><?php if($_SERVER['REQUEST_METHOD']!=='POST'):?><form method="post"><button class="btn">Aplicar actualización V10</button></form><?php else:?><p><a class="btn" href="expediente360.php">Abrir Expediente 360°</a></p><p>Después de verificar, elimina <code>instalar_expediente360_v10.php</code>.</p><?php endif;?></div></div></body></html>